"""add duration and buget to Post

Revision ID: 46299220652c
Revises: 9b3c02f1863a
Create Date: 2022-03-25 15:18:28.232029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46299220652c'
down_revision = '9b3c02f1863a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'budget')
    op.drop_column('post', 'duration')
    # ### end Alembic commands ###
