"""add images_url to post

Revision ID: 9cbd430b92a7
Revises: a0963fb748b1
Create Date: 2022-03-25 15:44:47.667681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbd430b92a7'
down_revision = 'a0963fb748b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('images_url', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'images_url')
    # ### end Alembic commands ###
