"""add destination to post

Revision ID: a0963fb748b1
Revises: 46299220652c
Create Date: 2022-03-25 15:25:12.750351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0963fb748b1'
down_revision = '46299220652c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'destination', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'destination_id')
    # ### end Alembic commands ###
