"""migration user

Revision ID: f7a1cac09ba8
Revises: ba5e1dd0f701
Create Date: 2022-01-14 17:54:04.560481

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f7a1cac09ba8'
down_revision = 'ba5e1dd0f701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination')
    op.add_column('user', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.create_table('destination',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='destination_pkey'),
    sa.UniqueConstraint('name', name='destination_name_key')
    )
    # ### end Alembic commands ###
