"""empty message

Revision ID: fac5d8db0548
Revises: 4ab02040f372
Create Date: 2022-01-27 14:50:50.881785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac5d8db0548'
down_revision = '4ab02040f372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('destination_name_key', 'destination', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('destination_name_key', 'destination', ['name'])
    # ### end Alembic commands ###
